name: Sync to Public Repo

on:
  push:
    branches:
      - main
      - prod

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to push tags and full history if needed

      - name: Set Git user identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add public repo as remote and push branch
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          echo "Adding remote 'public'..."
          git remote add public "https://x-access-token:${TOKEN}@github.com/mrgnlabs/mrgn-ts.git"
          git remote -v  # optional: confirm it's added

          echo "Pushing branch ${GITHUB_REF_NAME} to public repo..."
          git push public HEAD:refs/heads/${GITHUB_REF_NAME} --force
